/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab6_hectorreyes;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.security.Principal;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Onasis Reyes
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jD_modificarPlayList = new javax.swing.JDialog();
        jD_modificarCancion = new javax.swing.JDialog();
        jD_crearPlayList = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jT_nombreCancion = new javax.swing.JTextField();
        jT_año = new javax.swing.JTextField();
        jT_artista = new javax.swing.JTextField();
        jSp_puntuacionPlayList = new javax.swing.JSpinner();
        btn_aggCancion = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTbl_canciones = new javax.swing.JTable();
        btn_removerDeLaTabla = new javax.swing.JButton();
        btn_cleanJtable = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jT_nombreAlbum = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMI_modificar = new javax.swing.JMenuItem();
        jMI_eliminarRegistro = new javax.swing.JMenuItem();
        jMI_buscarPlayList = new javax.swing.JMenuItem();
        jMIT_guardarCancion = new javax.swing.JMenuItem();
        jMI_CrearPlayList = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jD_modificarPlayListLayout = new javax.swing.GroupLayout(jD_modificarPlayList.getContentPane());
        jD_modificarPlayList.getContentPane().setLayout(jD_modificarPlayListLayout);
        jD_modificarPlayListLayout.setHorizontalGroup(
            jD_modificarPlayListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jD_modificarPlayListLayout.setVerticalGroup(
            jD_modificarPlayListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jD_modificarCancionLayout = new javax.swing.GroupLayout(jD_modificarCancion.getContentPane());
        jD_modificarCancion.getContentPane().setLayout(jD_modificarCancionLayout);
        jD_modificarCancionLayout.setHorizontalGroup(
            jD_modificarCancionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 485, Short.MAX_VALUE)
        );
        jD_modificarCancionLayout.setVerticalGroup(
            jD_modificarCancionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 376, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jD_crearPlayListLayout = new javax.swing.GroupLayout(jD_crearPlayList.getContentPane());
        jD_crearPlayList.getContentPane().setLayout(jD_crearPlayListLayout);
        jD_crearPlayListLayout.setHorizontalGroup(
            jD_crearPlayListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jD_crearPlayListLayout.setVerticalGroup(
            jD_crearPlayListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Nombre de la Canción");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Puntuación de la PlayList");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Año en que salió la PlayList");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Artista del Álbum");

        jSp_puntuacionPlayList.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));

        btn_aggCancion.setText("Agregar Canción a la Tabla");
        btn_aggCancion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_aggCancionActionPerformed(evt);
            }
        });

        jTbl_canciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Canción", "Año de Estreno", "Artista del álbum", "Puntuación", "Nombre del Álbum"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTbl_canciones);

        btn_removerDeLaTabla.setText("Remover de la Tabla");
        btn_removerDeLaTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_removerDeLaTablaActionPerformed(evt);
            }
        });

        btn_cleanJtable.setText("Limpiar Tabla");
        btn_cleanJtable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cleanJtableActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Nombre del Álbum");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(95, 95, 95))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel5))
                                .addGap(35, 35, 35)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jT_artista, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                            .addComponent(jT_año, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jT_nombreCancion, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jT_nombreAlbum, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_aggCancion, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                            .addComponent(btn_removerDeLaTabla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_cleanJtable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(102, 102, 102))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(46, 46, 46)
                                .addComponent(jSp_puntuacionPlayList, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 661, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jT_nombreCancion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_aggCancion))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jT_año, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_removerDeLaTabla))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jT_artista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_cleanJtable))
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jT_nombreAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jSp_puntuacionPlayList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jMenu1.setText("Menu");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMI_modificar.setText("Modificar");
        jMI_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMI_modificarActionPerformed(evt);
            }
        });
        jMenu1.add(jMI_modificar);

        jMI_eliminarRegistro.setText("Eliminar Registro");
        jMI_eliminarRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMI_eliminarRegistroActionPerformed(evt);
            }
        });
        jMenu1.add(jMI_eliminarRegistro);

        jMI_buscarPlayList.setText("Buscar PlayList");
        jMI_buscarPlayList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMI_buscarPlayListActionPerformed(evt);
            }
        });
        jMenu1.add(jMI_buscarPlayList);

        jMIT_guardarCancion.setText("Guardar Cambios PlayList");
        jMIT_guardarCancion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIT_guardarCancionActionPerformed(evt);
            }
        });
        jMenu1.add(jMIT_guardarCancion);

        jMI_CrearPlayList.setText("Crear PlayList");
        jMI_CrearPlayList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMI_CrearPlayListActionPerformed(evt);
            }
        });
        jMenu1.add(jMI_CrearPlayList);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_aggCancionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_aggCancionActionPerformed
        // TODO add your handling code here:
        String[] nRow = {
            jT_nombreCancion.getText(),
            jT_año.getText(),
            jT_artista.getText(),
            jSp_puntuacionPlayList.getValue() + "",
            jT_nombreAlbum.getText()};
        DefaultTableModel model = (DefaultTableModel) jTbl_canciones.getModel();
        model.addRow(nRow);
        jTbl_canciones.setModel(model);
        jT_año.setText("");
        jT_nombreCancion.setText("");
        jT_nombreAlbum.setText("");
        jT_artista.setText("");
        jSp_puntuacionPlayList.setValue(0);
    }//GEN-LAST:event_btn_aggCancionActionPerformed

    private void btn_removerDeLaTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_removerDeLaTablaActionPerformed
        // TODO add your handling code here:
        if (jTbl_canciones.getSelectedRow() >= 0) {
            DefaultTableModel model = (DefaultTableModel) jTbl_canciones.getModel();
            model.removeRow(jTbl_canciones.getSelectedRow());
            jTbl_canciones.setModel(model);
        }

    }//GEN-LAST:event_btn_removerDeLaTablaActionPerformed

    private void jMIT_guardarCancionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIT_guardarCancionActionPerformed
        // TODO add your handling code here:
        if (archivoActual != null) {
            DefaultTableModel model = (DefaultTableModel) jTbl_canciones.getModel();
            String acum = "";
            for (int i = 0; i < model.getRowCount(); i++) {
                for (int j = 0; j < model.getColumnCount(); j++) {
                    acum += model.getValueAt(i, j).toString() + ";";
                }
                acum += "\n";
            }
            if (acum.length() >= 1) {
                acum = acum.substring(0, acum.length() - 1);
            }
            // acum = acum.replace(";", "|");
            FileWriter fw;
            try {
                fw = new FileWriter(archivoActual);
                try (BufferedWriter bw = new BufferedWriter(fw)) {
                    bw.write(acum);
                    bw.flush();
                    JOptionPane.showMessageDialog(this, "Se han guardado los cambios.");
                }
                fw.close();
            } catch (IOException ex) {
                Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            jMI_CrearPlayListActionPerformed(evt);
        }
    }//GEN-LAST:event_jMIT_guardarCancionActionPerformed

    private void jMI_buscarPlayListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMI_buscarPlayListActionPerformed
        // TODO add your handling code here:
        File fichero = null;
        FileReader fr = null;
        BufferedReader br = null;
        cleanJtable();
        DefaultTableModel model = (DefaultTableModel) jTbl_canciones.getModel();
        try {
            JFileChooser jfc = new JFileChooser("./");
            FileNameExtensionFilter filtro
                    = new FileNameExtensionFilter(
                            "Archivos de Texto", "txt");
            jfc.setFileFilter(filtro);
            int seleccion = jfc.showOpenDialog(this);
            if (seleccion == JFileChooser.APPROVE_OPTION) {
                fichero = jfc.getSelectedFile();
                archivoActual = jfc.getSelectedFile();
                fr = new FileReader(fichero);
                br = new BufferedReader(fr);
                String linea;
                cleanJtable();
                while ((linea = br.readLine()) != null) {
                    //  linea = linea.replace(";", "|");
                    String[] filas = linea.split(";");
                    model.addRow(filas);
                }
                br.close();
                fr.close();
            } //fin if
        } catch (Exception e) {
        }
        try {
            br.close();
            fr.close();
        } catch (IOException ex) {
        }
        jTbl_canciones.setModel(model);
    }//GEN-LAST:event_jMI_buscarPlayListActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void btn_cleanJtableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cleanJtableActionPerformed
        // TODO add your handling code here:
        cleanJtable();
    }//GEN-LAST:event_btn_cleanJtableActionPerformed

    private void jMI_CrearPlayListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMI_CrearPlayListActionPerformed
        // TODO add your handling code here:
        if (jTbl_canciones.getSelectedRow() >= 0) {
            // String nombrePlayList = JOptionPane.showInputDialog("Ingrese el nombre de la PlayList");
            JFileChooser jfc = new JFileChooser();
            FileNameExtensionFilter filtro = new FileNameExtensionFilter("Archivos de Texto", "txt");//"txt"
            jfc.setFileFilter(filtro);
            int seleccion = jfc.showSaveDialog(this);
            FileWriter fw = null;
            BufferedWriter bw = null;
            if (seleccion == JFileChooser.APPROVE_OPTION) {
                try {
                    File file = null;
                    if (jfc.getFileFilter().getDescription().equals("Archivos de Texto")) {
                        file = new File(jfc.getSelectedFile().getPath() + ".txt");
                    } else {
                        file = jfc.getSelectedFile();
                    }
                    archivoActual = file;
                    PlayList playList = new PlayList(jfc.getSelectedFile().getPath(), jfc.getSelectedFile().getPath());
                    playListActual = playList;
                    fw = new FileWriter(file);
                    bw = new BufferedWriter(fw);
                    DefaultTableModel model = (DefaultTableModel) jTbl_canciones.getModel();
                    String acum = "";
                    for (int i = 0; i < model.getRowCount(); i++) {
                        for (int j = 0; j < model.getColumnCount(); j++) {
                            acum += model.getValueAt(i, j) + ";";
                        }//fin for
                        acum += "\n";
                    }//fin for
                    //acum = acum.substring(0, acum.length()-1);
                    //acum = acum.replace(";", "|");
                    bw.write(acum);
                    bw.flush();
                    bw.close();
                    fw.close();
                    JOptionPane.showMessageDialog(this,
                            "PlayList Creada");
                } catch (IOException io) {
                    JOptionPane.showMessageDialog(this,
                            "Ha ocurrido un error y no se ha podido crear la PlayList");
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "No hay una canción seleccionada para la creación de una playList.");
        }
    }//GEN-LAST:event_jMI_CrearPlayListActionPerformed

    private void jMI_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMI_modificarActionPerformed
        // TODO add your handling code here:

        DefaultTableModel model = (DefaultTableModel) jTbl_canciones.getModel();
        if (jTbl_canciones.getSelectedRow() >= 0) {
            int col = -1;
            while (col < 0 || col > 4) {
                col = Integer.parseInt(JOptionPane.showInputDialog("Ingrese la columna de la fila seleccionada  [0,1,2,3,4,5]: "));
            }
            switch (col) {
                case 0:
                    String nombreCancion = JOptionPane.showInputDialog("Ingrese nuevo nombre de la cancion");
                    break;
                case 1:
                    int puntuacion = -1;
                    while (puntuacion < 0 || puntuacion > 10) {
                        puntuacion = Integer.parseInt(JOptionPane.showInputDialog("Ingrese nueva puntiación: [1-10]"));
                    }
                    String puntuacionCancion = puntuacion + "";
                    break;
                case 2:
                    String año = JOptionPane.showInputDialog("Ingrese nuevo año");
                    break;
                case 3:
                    String nombreArtista = JOptionPane.showInputDialog("Nuevo nombre del artista");
                    break;
                case 4:
                    String nombreAlbum = JOptionPane.showInputDialog("Nuevo nombre del álbum");
                    break;
                    
                    
                    
            }
            
            
            
        } else {
            JOptionPane.showMessageDialog(this, "No hay canción seleccionada");
        }
    }//GEN-LAST:event_jMI_modificarActionPerformed

    private void jMI_eliminarRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMI_eliminarRegistroActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_jMI_eliminarRegistroActionPerformed

    /**
     * @param args the command line arguments
     */
    public void cleanJtable() {
        jTbl_canciones.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{},
                new String[]{
                    "Canción", "Año de Estreno", "Artista del álbum", "Puntuación", "Nombre del Álbum"
                }
        ) {
            Class[] types = new Class[]{
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }
        });
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_aggCancion;
    private javax.swing.JButton btn_cleanJtable;
    private javax.swing.JButton btn_removerDeLaTabla;
    private javax.swing.JDialog jD_crearPlayList;
    private javax.swing.JDialog jD_modificarCancion;
    private javax.swing.JDialog jD_modificarPlayList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuItem jMIT_guardarCancion;
    private javax.swing.JMenuItem jMI_CrearPlayList;
    private javax.swing.JMenuItem jMI_buscarPlayList;
    private javax.swing.JMenuItem jMI_eliminarRegistro;
    private javax.swing.JMenuItem jMI_modificar;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSp_puntuacionPlayList;
    private javax.swing.JTextField jT_artista;
    private javax.swing.JTextField jT_año;
    private javax.swing.JTextField jT_nombreAlbum;
    private javax.swing.JTextField jT_nombreCancion;
    private javax.swing.JTable jTbl_canciones;
    // End of variables declaration//GEN-END:variables
     private PlayList playListActual = null;
    private File archivoActual = null;
    private ArrayList<PlayList> playsLists = new ArrayList();
}

/*
 Cancion cancion = new Cancion(
                    jT_nombreCancion.getText(),
                    jSp_puntuacionPlayList.getValue() + "",
                    jT_año.getText(),
                    jT_artista.getText(),
                    jT_nombreAlbum.getText());
            PlayList nPlayList = new PlayList(nombrePlayList);
            nPlayList.añadirCancion(cancion);
            try {
                nPlayList.escribirArchivo();
            } catch (IOException ex) {
                Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
            }
 */
